---
title: "juntos"
author: "Ritika Agarwal"
date: "2/21/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(haven)

yc_sib <- read_dta("C:/Users/Ritika Agarwal/Desktop/Paris School of Economics/Econometrics Project/Metrics Project/peru_r5/pe_yc_sib_anon/pe_r5_ycsib_ycsibling.dta")

index_sibR1R4_IV <- read_dta("C:/Users/Ritika Agarwal/Desktop/Paris School of Economics/Econometrics Project/Metrics Project/index_sibR1R4_IV.dta")

peru_constructed <- read_dta("C:/Users/Ritika Agarwal/Desktop/Paris School of Economics/Econometrics Project/Metrics Project/peru_constructed.dta")
```



```{r}
#Goal of this code chunk:
#prove that we find the same results as the authors in terms of descriptive statistics
#therefore,  we assume that this condition allows us to find the treated and the untreated)
#juntos<-peru_constructed%>% select(CHILDID,agemon,juntos,yc,round,inround)
juntos<-index_sibR1R4_IV %>% mutate(treated=ifelse(juntosgroup==1,1,ifelse(juntosgroup==2,NA,0)))


#stunt rate for older and younger sibling differentiated by sex
stunt_fem_old_r0_T<-mean(juntos$age[juntos$female==1 &juntos$round==0 & juntos$sib==0 & juntos$juntosgroup==1], na.rm=T)
stunt_mal_old_r0_T<-mean(juntos$age[juntos$female==0 &juntos$round==0& juntos$sib==0 & juntos$juntosgroup==1], na.rm=T)
stunt_fem_young_r0_T<-mean(juntos$age[juntos$female==1 &juntos$round==0& juntos$sib==1 & juntos$juntosgroup==1], na.rm=T)
stunt_mal_young_r0_T<-mean(juntos$age[juntos$female==0 &juntos$round==0& juntos$sib==1 & juntos$juntosgroup==1], na.rm=T)

stunt_fem_old_r0<-mean(juntos$age[juntos$female==1 &juntos$round==0 & juntos$sib==0 & juntos$juntosgroup==3], na.rm=T)
stunt_mal_old_r0<-mean(juntos$age[juntos$female==0 &juntos$round==0& juntos$sib==0 & juntos$juntosgroup==3], na.rm=T)
stunt_fem_young_r0<-mean(juntos$age[juntos$female==1 &juntos$round==0& juntos$sib==1 & juntos$juntosgroup==3], na.rm=T)
stunt_mal_young_r0<-mean(juntos$age[juntos$female==0 &juntos$round==0& juntos$sib==1 & juntos$juntosgroup==3], na.rm=T)

empty_df<-juntos[1,] 
df_1<-empty_df%>%select()%>% mutate(sex="Female")%>% mutate(round=0)%>%mutate(treated=1)%>% mutate(sib=0)%>% mutate(stunting=stunt_fem_old_r0_T)
df_2<-empty_df%>%select()%>% mutate(sex="Male")%>% mutate(round=0)%>%mutate(treated=1)%>% mutate(sib=0)%>%mutate(stunting=stunt_mal_old_r0_T)
df_3<-empty_df%>%select()%>% mutate(sex="Female")%>% mutate(round=0)%>%mutate(treated=1)%>% mutate(sib=1)%>%mutate(stunting=stunt_fem_young_r0_T)
df_4<-empty_df%>%select()%>% mutate(sex="Male")%>% mutate(round=0)%>%mutate(treated=1)%>% mutate(sib=1)%>%mutate(stunting=stunt_mal_young_r0_T)


df_5<-empty_df%>%select()%>% mutate(sex="Female")%>% mutate(round=0)%>%mutate(treated=0)%>% mutate(sib=0)%>% mutate(stunting=stunt_fem_old_r0)
df_6<-empty_df%>%select()%>% mutate(sex="Male")%>% mutate(round=0)%>%mutate(treated=0)%>% mutate(sib=0)%>%mutate(stunting=stunt_mal_old_r0)
df_7<-empty_df%>%select()%>% mutate(sex="Female")%>% mutate(round=0)%>%mutate(treated=0)%>% mutate(sib=1)%>%mutate(stunting=stunt_fem_young_r0)
df_8<-empty_df%>%select()%>% mutate(sex="Male")%>% mutate(round=0)%>%mutate(treated=0)%>% mutate(sib=1)%>%mutate(stunting=stunt_mal_young_r0)

stunt<-rbind(df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8)


mean(juntos$age[juntos$round==0 & juntos$sib==0 & juntos$juntosgroup==1 ], na.rm=T)#ok
mean(juntos$age[juntos$round==0 & juntos$sib==0 & juntos$juntosgroup==3 ], na.rm=T)#ok
mean(juntos$age[juntos$round==1 & juntos$sib==0 & juntos$juntosgroup==1 ], na.rm=T)# ok
mean(juntos$age[juntos$round==1 & juntos$sib==0 & juntos$juntosgroup==3 ], na.rm=T)# ok


mean(juntos$age[juntos$round==0 & juntos$sib==1 & juntos$juntosgroup==1 ], na.rm=T)#ok
mean(juntos$age[juntos$round==0 & juntos$sib==1 & juntos$juntosgroup==3 ], na.rm=T)#ok
mean(juntos$age[juntos$round==1 & juntos$sib==1 & juntos$juntosgroup==1 ], na.rm=T)#ok
mean(juntos$age[juntos$round==1 & juntos$sib==1 & juntos$juntosgroup==3 ], na.rm=T)#ok

#creating a dataframe in which i omitt juntosgroup==2
#I also create the interaction terms needed for the regression
#in my Vn what i mean is that you'd need to interact female with
#everything then things with each other, idk if that makes sense
#but basically if you follow the logic below youll get it, i am tired

adj<-juntos %>% filter(!is.na(treated)) %>% mutate(r_sib=round*sib)%>%mutate(r_treat=round*treated)%>%mutate(s_treat=sib*treated)%>%mutate(r_s_treat=round*sib*treated)

```


```{r}
#Note :`juntos data` set is data set from paper, `constructed data set` is the one from UK data service

#Objective of code:
#Find which childid is in both the constructed peru dataset and the one from the study.
#By doing that we will be able to conduct an analysis on the older child that were present in the paper.

peru_clean<-df%>%rename(CHILDID=childid) %>% filter(yc==1)
p<-peru_clean%>% filter(round==2|round==3)%>%select(CHILDID,yc,agemon,juntos)
#only selecting the younger cohort which has the older siblings and reducing the amount of variable for a clearer picture.
#we also filter for the rounds because the CHILDIDs appear twice for in the juntos data set
#filtering for rounds also allow us to compare the age observed to see if the data indeed matches


c<-magic_1%>% filter(sib==0) %>%mutate(treated=ifelse(rec_juntos==1,1,ifelse(rec_juntos==2,NA,0)))%>% filter(baselinejuntos==1)%>%
  select(CHILDID,treated,age_months,sib)
#we filter for only older siblings.
#previous text has shown us that the treated individuals are the ones for which this condition holds
#We create that variable in order to know which ones of the older siblings` childid should be considered
#the treated group in the control group in the constructed data set.
#I am not sure what juntos==2 is therefore I set is to 2 so that we can conserve the childID.
#we can figure out what it means afterwards

ok<-merge(c,p, by="CHILDID", all=TRUE) 
ok<- ok %>% filter(!is.na(sib))
#takes out observations that are in constructed but not in juntos data set.
# By taking out observation that are NA we take out those that are in the constructed data sets but not in juntos.


#The final result seems to make sense, the age are similar at the same round.
#We find that both variables for age_month do not exactly match but that is because of the merge function.
# If we were to individually select these CHILIDs in both data sets with just age_month and CHILD variable, we would see that
# they exactly match.
#Goal seems to have been achieved!

```

```{r}
#Objective of this code:
#We want, to only select these child IDs in the constructed one.
ok_1<-ok %>% select(CHILDID,treated)
#we only select the two variable of interest and create and new dataframe.

duplicated_df<-left_join(peru_clean,ok_1)
#we merge the two data sets to only have the same childids
#there are 5 times the same childid for each round.

#we therefore filter per round, take out the duplicated childIDs and rbind them
df_1<-duplicated_df %>% filter(round==1) %>% filter(!duplicated(CHILDID))
df_2<-duplicated_df %>% filter(round==2)%>% filter(!duplicated(CHILDID))
df_3<-duplicated_df %>% filter(round==3)%>% filter(!duplicated(CHILDID))
df_4<-duplicated_df %>% filter(round==4)%>% filter(!duplicated(CHILDID))
df_5<-duplicated_df %>% filter(round==5)%>% filter(!duplicated(CHILDID))



df_clean<-rbind(df_1,df_2,df_3,df_4,df_5)
df_clean<- df_clean %>% arrange(df_clean$CHILDID) %>%select(CHILDID,treated,yc:shother)%>%filter(!is.na(treated))
'This is the data set for the index child of the juntos study with the variables of the peru_constructed data set'
#we then arrange them to have per childid round 1 through 5 in an ordered manner.
# we leave out the ones for which treated is NA.
#We end up with the same number of households(if we consider each child id as a household) as in the juntos data set (843).
# The objective seems to have been reached!

```


```{r}
#Goal of this chunk:
# test whether we find the same stunting rate for older sibling treated and untreated than in the juntos data set
df_test<-df_clean%>% mutate(stunted=ifelse(stunting==1|stunting==2,1,0))%>%mutate(estunted=ifelse(stunting==2,1,0))
'this data frame has the selected older sibling data with the stunted variable and estunted variable created'

mean(df_test$stunted[df_test$round==4 & df_test$treated==1 ], na.rm=T)#ok
mean(df_test$stunted[df_test$round==5 & df_test$treated==1 ], na.rm=T)#ok
mean(df_test$stunted[df_test$round==4 & df_test$treated==0 ], na.rm=T)#ok
mean(df_test$stunted[df_test$round==5 & df_test$treated==0 ], na.rm=T)#ok


mean(juntos$stunted[juntos$round==0 & juntos$sib==0 & juntos$juntosgroup==1 ], na.rm=T)#ok
mean(juntos$stunted[juntos$round==0 & juntos$sib==0 & juntos$juntosgroup==3 ], na.rm=T)#ok
mean(juntos$stunted[juntos$round==1 & juntos$sib==0 & juntos$juntosgroup==1 ], na.rm=T)# ok
mean(juntos$stunted[juntos$round==1 & juntos$sib==0 & juntos$juntosgroup==3 ], na.rm=T)# ok

#there seems to be slight differences, this might be due to the rounding, it should not affect findings too much.

summary(df_clean_t$treated)
```





```{r}
#Goal of the chunk:
#we want to find a matching sample to make the groups for the older siblings more comparable.

library(MatchIt)

#steps:
#1. look at difference in terms of outcome of interest. 
#2.run a logit with variables of interest put the estimated coefficient in a list
#3.convert the list into a data frame with 2 columns, one with the predicted propensitiy score and the other for whether observation is treated of not. 

#tested for differences in some of the outcomes (1)
dif<-df_clean %>%filter(round==2)%>%
  group_by(treated) %>%
  summarise_all(funs(mean(., na.rm = T))) %>% filter(treated==1|treated==0)

#CAN USE THIS CODE TO SEE IF MATCHING WORKS
#creating a data set with the observations for which our variable for treated is either 0 or 1. Then created a bunch of new variables that are transformation of others.
#we do this because Andersen mentioned using these variables in his paper
df_clean_t<-df_test %>% filter(treated==1|treated==0) %>%filter(round==2)%>%mutate(U_6=(male05+female05)/hhsize)%>%
  mutate(B_6_17 = (male612+male1317+female612+female1317)/hhsize)%>%mutate(O_17 =1-U_6-B_6_17)%>% mutate(hhsize_2_4=ifelse(hhsize>=2&hhsize<=4,1,0))%>%mutate(hhsize_6_7=ifelse(hhsize>=6&hhsize<=7,1,0))%>%mutate(hhsize_8=ifelse(hhsize>=8,1,0))%>%mutate(hhsize_5=ifelse(hhsize==5,1,0))%>%mutate(foodsecdum=ifelse(foodsec==1|foodsec==2,1,0))


#creating propensity score(2)
m_ps<-glm(treated ~ chsex+hhsize_2_4+hhsize_6_7+hhsize_8+hhsize_5+typesite+caredu+momedu+dadedu+U_6+B_6_17+O_17+chlang+caresex+credit+chethnic+preprim+dadlive+chldrel+timesch+careage+carerel+momlive+dadage+momage,family = binomial(), data = df_clean_t)

#predicted propsensity score in data set. (2)
prs_df <- data.frame(pr_score = predict(m_ps, type = "response"),
                     treated = m_ps$model$treated)
head(prs_df)


#verifying common support
labs <- paste("Treatement status:", c("treated", "control"))
prs_df %>%
  mutate(treated = ifelse(treated == 1, labs[1], labs[2])) %>%
  ggplot(aes(x = pr_score)) +
  geom_histogram(color = "white") +
  facet_wrap(~treated) +
  xlab("Probability of being treated") +
  theme_bw()

#creating new data set with no missing values for the coefficients used in logit regression
df_clean_nomiss <-df_clean_t %>% filter(!is.na(treated))%>% filter(!is.na(careage))%>% filter(!is.na(dadage))%>% filter(!is.na(momage))%>% filter(!is.na(dadedu))%>% filter(!is.na(momedu))%>% filter(!is.na(agemon))%>%filter(!is.na(chlang))%>% filter(!is.na(chheight))%>% filter(!is.na(chweight))%>% filter(!is.na(zbfa))%>% filter(!is.na(zwfa))%>% filter(!is.na(stunted))%>% filter(!is.na(estunted))%>% filter(!is.na(caresex))%>% filter(!is.na(carecantread))%>% filter(!is.na(wi))%>% filter(!is.na(drwaterq))%>% filter(!is.na(toiletq))%>% filter(!is.na(hhsize))%>% filter(!is.na(hq))%>% filter(!is.na(sv))%>% filter(!is.na(cd))%>% filter(!is.na(elecq))%>% filter(!is.na(credit))%>% filter(!is.na(foodsec))%>% filter(!is.na(chsex))%>% filter(!is.na(momage))%>% filter(!is.na(dadage))%>% filter(!is.na(momlive))%>% filter(!is.na(timesch))%>% filter(!is.na(chldrel))
# MatchIt does not allow missing values 


mod_match <- matchit(treated ~ chsex+hhsize_2_4+hhsize_6_7+hhsize_8+hhsize_5+typesite+caredu+momedu+dadedu+U_6+B_6_17+chlang+caresex+credit+chethnic+preprim+dadlive+chldrel+O_17+timesch+careage+carerel+dadage+momlive+momage,method = "nearest", data = df_clean_nomiss)


dta_m <- match.data(mod_match)
'Data set with matched observations'
dim(dta_m)
#tells us how successful matching has been
summary(mod_match) 
```



```{r}
#Goal of code chunk:
#We want to select the CHILDIDs of the older siblings we matched previously.
#Doing so will allow us to have both pre and post treatment variables.

#creating the variables used by andersen in his paper
df_clean_match<-df_test %>% filter(round==3)%>%mutate(U_6=(male05+female05)/hhsize)%>%
  mutate(B_6_17 = (male612+male1317+female612+female1317)/hhsize)%>%mutate(O_17 =1-U_6-B_6_17)%>% mutate(hhsize_2_4=ifelse(hhsize>=2&hhsize<=4,1,0))%>%mutate(hhsize_6_7=ifelse(hhsize>=6&hhsize<=7,1,0))%>%mutate(hhsize_8=ifelse(hhsize>=8,1,0))%>%mutate(hhsize_5=ifelse(hhsize==5,1,0))%>%mutate(foodsecdum=ifelse(foodsec==1|foodsec==2,1,0))

#creating data set with the childids that we will use to merge
dta_m_mer<-dta_m%>% select(CHILDID)

#creating a data set with the chidids from matching but in round 3
match_3<-merge(df_clean_match,dta_m_mer,by="CHILDID")
dta_mer<-dta_m %>%select(CHILDID:foodsecdum)

#creating the data set with matched observations both in round 2 and 3
match_2_3<-rbind(dta_mer,match_3)
'Data set with matched older siblings round 2 and 3 with constructed variable'

#creating a bunch of indicator dummies necessary for  the regression with fixed effects
match_2_3<-match_2_3 %>% mutate(round=ifelse(round==3,1,0)) %>% mutate(r_t=treated*round)%>%mutate(age=agemon/12)%>%mutate(age_4_5=ifelse(age>4 & age<5& round==0,4,5))%>%mutate(age_7_8=ifelse(age>7 & age<8 & round==1,7,8))%>%mutate(age=ifelse(round==0,age_4_5,age_7_8))%>%mutate(age_4=ifelse(age==4,1,0))%>%mutate(age_5=ifelse(age==5,1,0))%>%mutate(age_7=ifelse(age==7,1,0))%>%mutate(age_8=ifelse(age==8,1,0))

```

```{r}
##Goal of this code chunk:
##reproduce authors findings by running regression with fixed effects
## we do this so that we know what exactly we should put in the regression before applying it to the matched data.


#Trying to create a data frame from the juntos data with only younger siblings.
#we filtered for only the observations considered in the study, by using baseline==1 and created a set of dummies necessary for the regression
y_s<-magic_1%>%filter(sib==1)%>%mutate(age_4=ifelse(age==4,1,0))%>%mutate(age_5=ifelse(age==5,1,0))%>%mutate(age_7=ifelse(age==7,1,0))%>%mutate(age_6=ifelse(age==6,1,0))%>%mutate(treated=ifelse(juntosgroup==1,1,ifelse(juntosgroup==2,NA,0)))%>% mutate(r_a=aftjuntosR3*round)%>%mutate(age_8=ifelse(age==8,1,0))%>%mutate(age_9=ifelse(age==9,1,0))%>%mutate(age_10=ifelse(age==10,1,0))%>% mutate(Iybirth_01=ifelse(ybirth==2001,1,0))%>%mutate(Iybirth_02=ifelse(ybirth==2002,1,0))%>%mutate(Iybirth_03=ifelse(ybirth==2003,1,0))%>%mutate(Iybirth_04=ifelse(ybirth==2004,1,0))%>%mutate(Iybirth_05=ifelse(ybirth==2005,1,0))%>%mutate(Iybirth_06=ifelse(ybirth==2006,1,0))%>%mutate(Iybirth_07=ifelse(ybirth==2007,1,0))%>%mutate(Iybirth_08=ifelse(ybirth==2008,1,0)) %>%
  mutate(ppvt_sp = ifelse(ppvtlang== 4, 1, 0))%>%
  mutate(ppvt_spq= ifelse(ppvtlang==3, 1, 0))%>%
  mutate(ppvt_q= ifelse(ppvtlang== 2,1,0))%>%
  mutate(ppvt_oth= ifelse(ppvtlang== 1,1,0))%>%filter(!is.na(treated))%>%filter(!(rec_juntos==2))%>%mutate(estunted=as.numeric(estunted))%>%mutate(stunted=as.numeric(stunted))%>% filter(baselinejuntos==1)

#attempt at regression with fixed effects
library(plm)
a<-lm(zhfa~round+rec_juntos+aftjuntosR3+prom_nbi+age_5+age_6+age_7+age_8+factor(CHILDID)+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02,data=y_s)

reg_estunted<-plm(estunted~round+rec_juntos+aftjuntosR3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08,data=y_s,index=c("CHILDID"),model = "within")#significant, basically what the authors found

reg_stunted<-plm(stunted~round+rec_juntos+aftjuntosR3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08,data=y_s,index=c("CHILDID"),model = "within")

reg_ppvt<-plm(std_PPVT~ppvt_sp+ppvt_spq+ppvt_q+ppvt_oth+round+rec_juntos+aftjuntosR3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08,data=y_s,index=c("CHILDID"),model = "within")# not significant, different than what authors found

reg_zhfa<-plm(zhfa~round+rec_juntos+aftjuntosR3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08,data=y_s,index=c("CHILDID"),model = "within")#significant, similar but not the same




#seem to have worked! (EXCEPT PPVT)
summary(reg_zhfa)
summary(reg_ppvt)
summary(reg_estunted)
summary(reg_stunted)

```

```{r}
unique(y_s$ybirth)
```




```{r}

##Goal of chunk:
## using this to 
last<- dta_m %>%
  group_by(treated) %>%
  summarise_all(funs(mean))

with(dta_m, t.test(wi ~ treated))
with(dta_m, t.test(zwfa ~ treated))
with(dta_m, t.test(zwfl ~ treated))
with(dta_m, t.test(chweight ~ treated))
with(dta_m, t.test(chheight ~ treated))
with(dta_m, t.test(momedu ~ treated))
with(dta_m, t.test(agemon ~ treated))

```

```{r}
#younger siblings

#Goal of the chunk:
#we want to compute matching for the younger siblings
#steps 
#1. We already have the childID relevant in df_clean
#2. We need to filter for these childID in the juntos data set
#3. We want to add the caregiver variable
#4.conduct matching

#1./ 2.

df_clean_ID<-df_clean %>%filter(round==3|round==4)%>%select(CHILDID)
df_juntos<- magic_1 %>% filter(sib==1)

df_duplicatsib<-left_join(df_clean_ID,df_juntos,by="CHILDID", all=TRUE)
df_1<-df_duplicatsib %>% filter(round==0) %>% filter(!duplicated(CHILDID))
df_2<-df_duplicatsib %>% filter(round==1)%>% filter(!duplicated(CHILDID))

df_mergsib<-rbind(df_1,df_2)
df_mergsib<-df_mergsib%>%arrange(df_mergsib$CHILDID)
df_clean_3_4cg<-df_clean %>% filter(round==3|round==4) %>% select(careage,caresex,caredu)
df_mergsib<-cbind(df_mergsib,df_clean_3_4cg)

df_mergsib<-df_mergsib%>%mutate(treated=ifelse(rec_juntos==1,1,ifelse(rec_juntos==2,NA,0)))%>%filter(!is.na(treated)) %>%select(CHILDID,treated,rec_juntos,sib:caredu)%>%mutate(ben=ifelse(juntosgroup==1,1,ifelse(juntosgroup==2,NA,0)))%>%filter(!is.na(ben))
identical(df_mergsib$treated,df_mergsib$rec_juntos)

#step1-3 reached


library(MatchIt)

#first look at difference in terms of outcome of interest.

#tested for differences in some of the outcomes


df_clean_t<-df_mergsib%>%filter(round==0)

#with(df_clean_t, t.test(careage ~ treated))
#with(df_clean_t, t.test(dadage ~ treated))
#with(df_clean_t, t.test(momage ~ treated))
#with(df_clean_t, t.test(caredu ~ treated))
#with(df_clean_t, t.test(dadedu ~ treated))
#with(df_clean_t, t.test(momedu ~ treated))
#with(df_clean_t, t.test(agemon ~ treated))
#very different in a lot of regards


#creating propensity score
m_ps_ys<-glm(rec_juntos ~ METH+CAREED+MUMED+female+BWGHT+rural+caresex+careage+caredu,family = binomial(), data = df_clean_t)


prs_df_ys <- data.frame(pr_score = predict(m_ps_ys, type = "response"),
                     treated = m_ps_ys$model$rec_juntos)
head(prs_df_ys)

#verifying common support
labs <- paste("Treatement status:", c("treated", "control"))
prs_df_ys %>%
  mutate(rec_juntos = ifelse(treated== 1, labs[1], labs[2])) %>%
  ggplot(aes(x = pr_score)) +
  geom_histogram(color = "white") +
  facet_wrap(~rec_juntos) +
  xlab("Probability of being treated") +
  theme_bw()


df_clean_nomiss_ys <-df_clean_t %>% filter(!is.na(rec_juntos))%>% filter(!is.na(METH))%>% filter(!is.na(CAREED))%>% filter(!is.na(MUMED))%>% filter(!is.na(tipom2R1))%>% filter(!is.na(tipom3R1))%>% filter(!is.na(caredu))%>%filter(!is.na(BWGHT))%>% filter(!is.na(hh_agricR1))%>% filter(!is.na(female))%>% filter(!is.na(careage))%>% filter(!is.na(caresex))%>% filter(!is.na(rural))
# MatchIt does not allow missing values 


mod_match_ys <- matchit(rec_juntos ~  METH+CAREED+MUMED+female+BWGHT+rural+caresex+careage+caredu,method = "nearest", data = df_clean_nomiss_ys)

dta_m_ys <- match.data(mod_match_ys)
dim(dta_m_ys)


summary(mod_match_ys) 

dta_m_ys_CI<-dta_m_ys %>%select(CHILDID)
df_mergsib_1<-df_mergsib%>%filter(round==0)
ys_comm_supp<-left_join(dta_m_ys_CI,df_mergsib)

```


```{r}
#older siblings

df_clean_ID_os<-df_clean %>%filter(round==2|round==3)%>%select(CHILDID)
df_juntos_os<- magic_1 %>% filter(sib==0)

df_duplicat_os<-left_join(df_clean_ID_os,df_juntos_os,by="CHILDID", all=TRUE)
df_1_os<-df_duplicat_os %>% filter(round==0) %>% filter(!duplicated(CHILDID))
df_2_os<-df_duplicat_os %>% filter(round==1)%>% filter(!duplicated(CHILDID))

df_merg_os<-rbind(df_1_os,df_2_os)
df_merg_os<-df_merg_os%>%arrange(df_merg_os$CHILDID)
df_clean_2_3cg<-df_clean %>% filter(round==2|round==3) %>% select(careage,caresex,caredu)
df_merg_os<-cbind(df_merg_os,df_clean_2_3cg)

df_merg_os<-df_merg_os%>%mutate(treated=ifelse(rec_juntos==1,1,ifelse(rec_juntos==2,NA,0)))%>%filter(!is.na(treated))%>%select(CHILDID,treated,rec_juntos,sib:caredu)

#first look at difference in terms of outcome of interest.

#tested for differences in some of the outcomes


df_clean_t_os<-df_merg_os%>%filter(round==0)

#with(df_clean_t, t.test(careage ~ treated))
#with(df_clean_t, t.test(dadage ~ treated))
#with(df_clean_t, t.test(momage ~ treated))
#with(df_clean_t, t.test(caredu ~ treated))
#with(df_clean_t, t.test(dadedu ~ treated))
#with(df_clean_t, t.test(momedu ~ treated))
#with(df_clean_t, t.test(agemon ~ treated))
#very different in a lot of regards


#creating propensity score
m_ps_os<-glm(rec_juntos ~ METH+CAREED+MUMED+female+BWGHT+rural+caresex+careage+caredu,family = binomial(), data = df_clean_t_os)


prs_df_os <- data.frame(pr_score = predict(m_ps_os, type = "response"),
                     treated = m_ps_os$model$rec_juntos)
head(prs_df_os)

#verifying common support
labs <- paste("Treatement status:", c("treated", "control"))
prs_df_os %>%
  mutate(rec_juntos = ifelse(treated== 1, labs[1], labs[2])) %>%
  ggplot(aes(x = pr_score)) +
  geom_histogram(color = "white") +
  facet_wrap(~rec_juntos) +
  xlab("Probability of being treated") +
  theme_bw()


df_clean_nomiss_os <-df_clean_t_os %>% filter(!is.na(rec_juntos))%>% filter(!is.na(METH))%>% filter(!is.na(CAREED))%>% filter(!is.na(MUMED))%>% filter(!is.na(caredu))%>%filter(!is.na(BWGHT))%>% filter(!is.na(female))%>% filter(!is.na(careage))%>% filter(!is.na(caresex))%>% filter(!is.na(rural))
# MatchIt does not allow missing values 


mod_match_os <- matchit(rec_juntos ~  METH+CAREED+MUMED+female+BWGHT+rural+caresex+careage+caredu,method = "nearest", data = df_clean_nomiss_os)

dta_m_os <- match.data(mod_match_os)
dim(dta_m_os)


summary(mod_match_os) 



dta_m_os_CI<-dta_m_os %>%select(CHILDID)
df_mergsib_1<-df_merg_os%>%filter(round==0)
os_comm_supp<-left_join(dta_m_os_CI,df_merg_os)

ys_comm_supp$ben<-NULL

matched_dta<-rbind(ys_comm_supp,os_comm_supp)
matched_dta<-matched_dta %>%arrange(matched_dta$CHILDID)

```

```{r}
#descriptive statistics part

'#Stunted
##Matched

####younger sibling'

mean(matched_dta$stunted[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated
mean(matched_dta$stunted[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated

mean(matched_dta$stunted[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==1], na.rm=T)#Untreated
mean(matched_dta$stunted[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(matched_dta$stunted[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated
mean(matched_dta$stunted[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated

mean(matched_dta$stunted[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==0], na.rm=T)#Untreated
mean(matched_dta$stunted[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==0], na.rm=T)#Untreated


'#Age
##Matched
###younger sibling'

mean(matched_dta$age[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated
mean(matched_dta$age[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated

mean(matched_dta$age[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==1], na.rm=T)#Untreated
mean(matched_dta$age[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(matched_dta$age[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated
mean(matched_dta$age[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated

mean(matched_dta$age[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==0], na.rm=T)#Untreated
mean(matched_dta$age[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==0], na.rm=T)#Untreated



'#severe stunting
##Matched
###younger sibling'

mean(matched_dta$estunted[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated
mean(matched_dta$estunted[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated

mean(matched_dta$estunted[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==1], na.rm=T)#Untreated
mean(matched_dta$estunted[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(matched_dta$estunted[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated
mean(matched_dta$estunted[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated

mean(matched_dta$estunted[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==0], na.rm=T)#Untreated
mean(matched_dta$estunted[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==0], na.rm=T)#Untreated


'#PPVT
##Matched
###younger sibling'

mean(matched_dta$std_PPVT[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated
mean(matched_dta$std_PPVT[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated

mean(matched_dta$std_PPVT[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==1], na.rm=T)#Untreated
mean(matched_dta$std_PPVT[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(matched_dta$std_PPVT[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated
mean(matched_dta$std_PPVT[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated

mean(matched_dta$std_PPVT[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==0], na.rm=T)#Untreated
mean(matched_dta$std_PPVT[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==0], na.rm=T)#Untreated



'#zhfa
##Matched
###younger sibling'

mean(matched_dta$zhfa[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated
mean(matched_dta$zhfa[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==1], na.rm=T)#treated

mean(matched_dta$zhfa[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==1], na.rm=T)#Untreated
mean(matched_dta$zhfa[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(matched_dta$zhfa[matched_dta$round==0 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated
mean(matched_dta$zhfa[matched_dta$round==1 & matched_dta$rec_juntos==1 & matched_dta$sib==0], na.rm=T)#treated

mean(matched_dta$zhfa[matched_dta$round==0 & matched_dta$rec_juntos==0& matched_dta$sib==0], na.rm=T)#Untreated
mean(matched_dta$zhfa[matched_dta$round==1 & matched_dta$rec_juntos==0 & matched_dta$sib==0], na.rm=T)#Untreated


```


```{r}
#descriptive statistics part
df_mergsib$ben<-NULL
not_matched_dta<-rbind(df_mergsib,df_merg_os)

'#Stunted
##not_matched

####younger sibling'

mean(not_matched_dta$stunted[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated
mean(not_matched_dta$stunted[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated

mean(not_matched_dta$stunted[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==1], na.rm=T)#Untreated
mean(not_matched_dta$stunted[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(not_matched_dta$stunted[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated
mean(not_matched_dta$stunted[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated

mean(not_matched_dta$stunted[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==0], na.rm=T)#Untreated
mean(not_matched_dta$stunted[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==0], na.rm=T)#Untreated


'#Age
##not_matched
###younger sibling'

mean(not_matched_dta$age[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated
mean(not_matched_dta$age[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated

mean(not_matched_dta$age[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==1], na.rm=T)#Untreated
mean(not_matched_dta$age[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(not_matched_dta$age[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated
mean(not_matched_dta$age[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated

mean(not_matched_dta$age[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==0], na.rm=T)#Untreated
mean(not_matched_dta$age[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==0], na.rm=T)#Untreated



'#severe stunting
##not_matched
###younger sibling'

mean(not_matched_dta$estunted[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated
mean(not_matched_dta$estunted[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated

mean(not_matched_dta$estunted[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==1], na.rm=T)#Untreated
mean(not_matched_dta$estunted[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(not_matched_dta$estunted[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated
mean(not_matched_dta$estunted[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated

mean(not_matched_dta$estunted[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==0], na.rm=T)#Untreated
mean(not_matched_dta$estunted[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==0], na.rm=T)#Untreated


'#PPVT
##not_matched
###younger sibling'

mean(not_matched_dta$std_PPVT[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated
mean(not_matched_dta$std_PPVT[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated

mean(not_matched_dta$std_PPVT[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==1], na.rm=T)#Untreated
mean(not_matched_dta$std_PPVT[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(not_matched_dta$std_PPVT[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated
mean(not_matched_dta$std_PPVT[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated

mean(not_matched_dta$std_PPVT[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==0], na.rm=T)#Untreated
mean(not_matched_dta$std_PPVT[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==0], na.rm=T)#Untreated



'#zhfa
##not_matched
###younger sibling'

mean(not_matched_dta$zhfa[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated
mean(not_matched_dta$zhfa[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==1], na.rm=T)#treated

mean(not_matched_dta$zhfa[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==1], na.rm=T)#Untreated
mean(not_matched_dta$zhfa[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==1], na.rm=T)#Untreated


'### older sibling'
mean(not_matched_dta$zhfa[not_matched_dta$round==0 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated
mean(not_matched_dta$zhfa[not_matched_dta$round==1 & not_matched_dta$rec_juntos==1 & not_matched_dta$sib==0], na.rm=T)#treated

mean(not_matched_dta$zhfa[not_matched_dta$round==0 & not_matched_dta$rec_juntos==0& not_matched_dta$sib==0], na.rm=T)#Untreated
mean(not_matched_dta$zhfa[not_matched_dta$round==1 & not_matched_dta$rec_juntos==0 & not_matched_dta$sib==0], na.rm=T)#Untreated

```

```{r}
matched_dta_1<-matched_dta%>%
  mutate(age_1= ifelse(age==1,1,0))%>%
  mutate(age_2= ifelse(age==2,1,0))%>%
  mutate(age_4= ifelse(age==4,1,0))%>%
  mutate(age_5= ifelse(age==5,1,0))%>%
  mutate(age_6= ifelse(age==6,1,0))%>%
  mutate(age_7= ifelse(age==7,1,0))%>%
  mutate(age_8= ifelse(age==8,1,0))%>%
  mutate(age_9= ifelse(age==9,1,0))%>%
  mutate(age_10= ifelse(age==10,1,0))%>%
  mutate(yob_00= ifelse(ybirth==2000,1,0))%>%
  mutate(yob_01= ifelse(ybirth==2001,1,0))%>%
  mutate(yob_02= ifelse(ybirth==2002,1,0))%>%
  mutate(yob_03= ifelse(ybirth==2003,1,0))%>%
  mutate(yob_04= ifelse(ybirth==2004,1,0))%>%
  mutate(yob_05= ifelse(ybirth==2005,1,0))%>%
  mutate(yob_06= ifelse(ybirth==2006,1,0))%>%
  mutate(yob_07= ifelse(ybirth==2007,1,0))%>%
  mutate(yob_08= ifelse(ybirth==2008,1,0))%>%
  mutate(childid= as.factor(CHILDID))%>%
  mutate(ppvt_sp = ifelse(ppvtlang== 4, 1, 0))%>%
  mutate(ppvt_spq= ifelse(ppvtlang==3, 1, 0))%>%
  mutate(ppvt_q= ifelse(ppvtlang== 2,1,0))%>%
  mutate(ppvt_oth= ifelse(ppvtlang== 1,1,0))%>%
  filter(!is.na(age))%>%filter(sib==0)%>%mutate(stunted=as.numeric(stunted))%>%mutate(estunted=as.numeric(estunted))

reg1<-plm(zhfa ~  round + rec_juntos + aftjuntosR3 + MUMED + CETH + wiR1 + female  + age_1 + age_2 + age_4 + age_5 + age_6 + age_7 + age_8 + age_9 + age_10 + yob_00 + yob_01 + yob_02 + yob_03 + yob_04 + yob_05 + yob_06 + yob_07 + yob_08  ,index = c("CHILDID"), data= matched_dta_1)

summary(reg1)

reg2<-plm(std_PPVT ~ round + rec_juntos + aftjuntosR3 + ppvt_sp + ppvt_spq + ppvt_q + ppvt_oth + MUMED + CETH + wiR1 + female  + age_1 + age_2 + age_4 + age_5 + age_6 + age_7 + age_8 + age_9 + age_10 + yob_00 + yob_01 + yob_02 + yob_03 + yob_04 + yob_05 + yob_06 + yob_07 + yob_08 ,index = c("CHILDID"), data= matched_dta_1, na.rm=T)

summary(reg2)


reg3<-plm(stunted ~ + round + rec_juntos + aftjuntosR3 + MUMED + CETH + wiR1 + female  + age_1 + age_2 + age_4 + age_5 + age_6 + age_7 + age_8 + age_9 + age_10 + yob_00 + yob_01 + yob_02 + yob_03 + yob_04 + yob_05 + yob_06 + yob_07 + yob_08,index = c("CHILDID"),data= matched_dta_1)

summary(reg3)

reg4<-plm(estunted ~ round  + MUMED + CETH + wiR1 + female  + age_1 + age_2 + age_4 + age_5 + age_6 + age_7 + age_8 + age_9 + age_10 + yob_00 + yob_01 + yob_02 + yob_03 + yob_04 + yob_05 + yob_06 + yob_07 + yob_08 + factor(childid),index=c("CHILDID"),data= matched_dta_1, na.rm=T)

summary(reg4)
```

```{r}
df_mergsibtest<-df_mergsib%>%mutate(age_4=ifelse(age==4,1,0))%>%mutate(age_5=ifelse(age==5,1,0))%>%mutate(age_7=ifelse(age==7,1,0))%>%mutate(age_6=ifelse(age==6,1,0))%>%mutate(treated=ifelse(juntosgroup==1,1,ifelse(juntosgroup==2,NA,0)))%>% mutate(r_a=aftjuntosR3*round)%>%mutate(age_8=ifelse(age==8,1,0))%>%mutate(age_9=ifelse(age==9,1,0))%>%mutate(age_10=ifelse(age==10,1,0))%>% mutate(Iybirth_01=ifelse(ybirth==2001,1,0))%>%mutate(Iybirth_02=ifelse(ybirth==2002,1,0))%>%mutate(Iybirth_03=ifelse(ybirth==2003,1,0))%>%mutate(Iybirth_04=ifelse(ybirth==2004,1,0))%>%mutate(Iybirth_05=ifelse(ybirth==2005,1,0))%>%mutate(Iybirth_06=ifelse(ybirth==2006,1,0))%>%mutate(Iybirth_07=ifelse(ybirth==2007,1,0))%>%mutate(Iybirth_08=ifelse(ybirth==2008,1,0)) %>%
  mutate(ppvt_sp = ifelse(ppvtlang== 4, 1, 0))%>%
  mutate(ppvt_spq= ifelse(ppvtlang==3, 1, 0))%>%
  mutate(ppvt_q= ifelse(ppvtlang== 2,1,0))%>%
  mutate(ppvt_oth= ifelse(ppvtlang== 1,1,0))%>%filter(!is.na(treated))%>%filter(!(rec_juntos==2))%>%mutate(estunted=as.numeric(estunted))%>%mutate(stunted=as.numeric(stunted))%>% filter(baselinejuntos==1)%>%mutate(caresex=ifelse(caresex==2,1,0))%>%mutate(care_round=caresex*round)%>%mutate(care_rec=caresex*rec_juntos)%>%mutate(care_rec_aft=caresex*aftjuntosR3)


reg_estunted<-plm(estunted~round+care_round+caresex+rec_juntos+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08,data=df_mergsibtest,index=c("CHILDID"),model = "within")#significant, basically what the authors found

reg_stunted<-plm(stunted~round+care_round+caresex+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08,data=df_mergsibtest,index=c("CHILDID"),model = "within")

reg_ppvt<-plm(std_PPVT~ppvt_sp+ppvt_spq+ppvt_q+ppvt_oth+round+care_round+caresex+rec_juntos+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08,data=df_mergsibtest,index=c("CHILDID"),model = "within")# not significant, different than what authors found

reg_zhfa<-plm(zhfa~round+care_round+caresex+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08,data=df_mergsibtest,index=c("CHILDID"),model = "within")#significant, similar but not the same

summary(reg_zhfa)
summary(reg_ppvt)
summary(reg_estunted)
summary(reg_stunted)
```

```{r,include=FALSE}
# Creating the 174 households treated. (it gives 174 so far)
df_treatment <- index_sibR1R4_IV %>% filter(yenrolljuntos ==2007 |yenrolljuntos ==2008| yenrolljuntos ==2009)
df_treatment <- df_treatment %>% filter(quintil==1 | quintil==2 | is.na(quintil))
df_treatment <- df_treatment%>% filter(juntosgroup==1)%>%
  filter(baselinejuntos==1)

# Creating the 509 households control. (it gives 517 so far)
df_never <- index_sibR1R4_IV  %>% filter(juntosgroup==3) %>%
  filter(baselinejuntos==1)

#f_never <- df_never %>% filter(quintil==1 | quintil==2 | is.na(quintil))
# I put everything together. 
new_df <- rbind(df_treatment, df_never)

new_df<-new_df%>%
  mutate(treated=ifelse(rec_juntos==1,1,ifelse(rec_juntos==2,NA,0)))

new_df_clean <-new_df %>%
  filter(!is.na(stunted))%>%
  filter(!is.na(estunted))%>%
  filter(!is.na(zhfa))%>%
  filter(!is.na(difstunted))%>%
  filter(!is.na(difestunted))%>%
  filter(!is.na(difzhfa))%>%
  filter(!is.na(treated))%>% 
  filter(!is.na(HHSIZER1))%>%
  filter(!is.na(female))%>%
  filter(!is.na(wiR1))%>%
  filter(!is.na(geo_index))%>%
  filter(!is.na(ruralR1))%>%
  filter(!is.na(totalexp_rpc))%>%
  filter(!is.na(age_months))%>%
  filter(!is.na(women_weducR1))%>%
  filter(!is.na(edu_men617R1))%>%
  filter(!is.na(serv3R1)) %>%
  filter(!is.na(combust)) %>%
  filter(!is.na(mum_analf)) %>%
  filter(!is.na(MUMED))

new_df_clean_R0<-new_df_clean%>%
  filter(round==0)

new_df_clean_R1<-new_df_clean%>%
  filter(round==1)

new_df_clean_old<-new_df_clean%>%
  filter(sib==0)

new_df_clean_y<-new_df_clean%>%
  filter(sib==1)

install.packages("optmatch")

#NB CLANG has na values for all the siblings 

mod_match <- matchit(treated ~ HHSIZER1 +female + wiR1 + geo_index + ruralR1 + totalexp_rpc + age_months + MUMED + edu_men617R1 + serv3R1, data = new_df_clean_R0,
                      method= "full" , distance="glm", link="probit")

summary(mod_match)

#we have 336 treated (both siblings and index) compared to 991 untreated using full matching

m.data1 <- match.data(mod_match)%>%
 select(CHILDID, sib, distance, weights, subclass)

m_dta_old<-m.data1%>%
  filter(sib==0)
  
m_dta_y<-m.data1%>%
  filter(sib==1)

matched_old<-merge(new_df_clean_old, m_dta_old, by=c("CHILDID","sib"))
matched_y<-merge(new_df_clean_y, m_dta_y, by=c("CHILDID","sib"))
  
matched_whole<-rbind(matched_old, matched_y)
```

```{r}

#trying to check robustness with matching 
#estimating eq 4

data_robust<-matched_whole%>%
mutate(age_4=ifelse(age==4,1,0))%>%
  mutate(age_5=ifelse(age==5,1,0))%>%
  mutate(age_7=ifelse(age==7,1,0))%>%
  mutate(age_6=ifelse(age==6,1,0))%>%
  mutate(age_8=ifelse(age==8,1,0))%>%
  mutate(age_9=ifelse(age==9,1,0))%>%
  mutate(age_10=ifelse(age==10,1,0))%>%
  mutate(age_1= ifelse(age==1, 1,0))%>%
  mutate(age_2= ifelse(age==2,1,0))%>%
  mutate(age_3= ifelse(age==3,1,0))%>%
  mutate(Iybirth_01=ifelse(ybirth==2001,1,0))%>%
  mutate(Iybirth_02=ifelse(ybirth==2002,1,0))%>%
  mutate(Iybirth_03=ifelse(ybirth==2003,1,0))%>%
  mutate(Iybirth_04=ifelse(ybirth==2004,1,0))%>%
  mutate(Iybirth_05=ifelse(ybirth==2005,1,0))%>%
  mutate(Iybirth_06=ifelse(ybirth==2006,1,0))%>%
  mutate(Iybirth_07=ifelse(ybirth==2007,1,0))%>%
  mutate(Iybirth_08=ifelse(ybirth==2008,1,0)) %>%
  mutate(Iybirth_09= ifelse(ybirth==2009,1,0))%>%
  mutate(ppvt_sp = ifelse(ppvtlang== 4, 1, 0))%>%
  mutate(ppvt_spq= ifelse(ppvtlang==3, 1, 0))%>%
  mutate(ppvt_q= ifelse(ppvtlang== 2,1,0))%>%
  mutate(ppvt_oth= ifelse(ppvtlang== 1,1,0))%>%
  filter(!(rec_juntos==2))%>%
  mutate(estunted=as.numeric(estunted))%>%
  mutate(stunted=as.numeric(stunted))%>% 
  filter(juntosgroup!=2)%>%
  filter(baselinejuntos==1)

data_robust_os<-data_robust%>%
  filter(sib==0)

data_robust_ys<-data_robust%>%
  filter(sib==1)

#eq4, stunted

reg_stdoc<-lm(stunted~round+rec_juntos+ aftjuntosR3 +age_1 + age_2 + age_3 +age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+ factor(CHILDID)
              ,data=data_robust_os, weights= weights)

summary(reg_stdoc)
coeftest(reg_stdoc,vcov=vcovHC(reg_stdoc, type="HC0", cluster="group"))


reg_stdyc<-lm(stunted~round+rec_juntos+ aftjuntosR3 + factor(CHILDID),
                data=data_robust_ys, weights= weights)

summary(reg_stdyc)
d<-coeftest(reg_stdyc, vcov=vcovHC(reg_stdyc, type="sss", cluster="group"))

stargazer(d)
```

```{r}

#PPVT 

new_df_ppvt<-new_df %>%
  filter(ppvtlang==4)%>%
  filter(!is.na(ppvtlang))%>%
  filter(!is.na(std_PPVT))%>%
  filter(!is.na(stunted))%>%
  filter(!is.na(estunted))%>%
  filter(!is.na(zhfa))%>%
  filter(!is.na(difstd_PPVT))%>%
  filter(!is.na(difstunted))%>%
  filter(!is.na(difestunted))%>%
  filter(!is.na(difzhfa))


#seperating it doesn't change anything we still have 883 households 
new_R0_ppvt<-new_df %>%
  filter(round==0)%>%
  filter(ppvtlang==4)%>%
  filter(!is.na(ppvtlang))%>%
  filter(!is.na(std_PPVT))%>%
  filter(!is.na(stunted))%>%
  filter(!is.na(estunted))%>%
  filter(!is.na(zhfa))%>%
  filter(!is.na(difstd_PPVT))%>%
  filter(!is.na(difstunted))%>%
  filter(!is.na(difestunted))%>%
  filter(!is.na(difzhfa))

new_R1_ppvt<-new_df %>%
  filter(round==1)%>%
  filter(ppvtlang==4)%>%
  filter(!is.na(ppvtlang))%>%
  filter(!is.na(std_PPVT))%>%
  filter(!is.na(stunted))%>%
  filter(!is.na(estunted))%>%
  filter(!is.na(zhfa))%>%
  filter(!is.na(difstd_PPVT))%>%
  filter(!is.na(difstunted))%>%
  filter(!is.na(difestunted))%>%
  filter(!is.na(difzhfa))

df_ppvt_test<- rbind(new_R0_ppvt, new_R1_ppvt)

#we should try to reduce further by filtering for rounds and thenmerging. #Iclean everything before Matchit and filter for round 0 for the whole sample and for the older sibling. 
```

```{r}

#GOAL: POOLED REGRESSION

#1. Replication eq5 using author's dataset 
#2. Matching robustness check using filtered dataset (NAs)
#3. Extension to caregiver's analysis

#1 Replication:
new_df<-new_df%>%
mutate(age_4=ifelse(age==4,1,0))%>%
  mutate(age_5=ifelse(age==5,1,0))%>%
  mutate(age_7=ifelse(age==7,1,0))%>%
  mutate(age_6=ifelse(age==6,1,0))%>%
  mutate(age_8=ifelse(age==8,1,0))%>%
  mutate(age_9=ifelse(age==9,1,0))%>%
  mutate(age_10=ifelse(age==10,1,0))%>%
  mutate(age_1= ifelse(age==1, 1,0))%>%
  mutate(age_2= ifelse(age==2,1,0))%>%
  mutate(age_3= ifelse(age==3,1,0))%>%
  mutate(Iybirth_01=ifelse(ybirth==2001,1,0))%>%
  mutate(Iybirth_02=ifelse(ybirth==2002,1,0))%>%
  mutate(Iybirth_03=ifelse(ybirth==2003,1,0))%>%
  mutate(Iybirth_04=ifelse(ybirth==2004,1,0))%>%
  mutate(Iybirth_05=ifelse(ybirth==2005,1,0))%>%
  mutate(Iybirth_06=ifelse(ybirth==2006,1,0))%>%
  mutate(Iybirth_07=ifelse(ybirth==2007,1,0))%>%
  mutate(Iybirth_08=ifelse(ybirth==2008,1,0)) %>%
  mutate(Iybirth_09= ifelse(ybirth==2009,1,0))%>%
  mutate(ppvt_sp = ifelse(ppvtlang== 4, 1, 0))%>%
  mutate(ppvt_spq= ifelse(ppvtlang==3, 1, 0))%>%
  mutate(ppvt_q= ifelse(ppvtlang== 2,1,0))%>%
  mutate(ppvt_oth= ifelse(ppvtlang== 1,1,0))%>%
  filter(!(rec_juntos==2))%>%
  mutate(estunted=as.numeric(estunted))%>%
  mutate(stunted=as.numeric(stunted))%>% 
  filter(juntosgroup!=2)%>%
  filter(baselinejuntos==1)


new_df_pooled<-new_df %>%
  mutate(time_1=1) %>%
  mutate(time_1= ifelse(round==1&sib==0, 2, ifelse(round==0&sib==1, 2, ifelse(round==1&sib==1, 3, NA))))%>%
  mutate(rounds_juntos=replace(time_1, is.na(time_1), 1))


new_df_pooled<-new_df_pooled%>%
  mutate(round3os= ifelse(rounds_juntos==2 & sib==0, 1, ifelse(rounds_juntos==2 & sib==1, 0, ifelse(rounds_juntos==1 & sib==0, 0, NA)))) %>%
  mutate(round4ys= ifelse(rounds_juntos==3 & sib==1, 1, ifelse(rounds_juntos==2 & sib==1, 0, ifelse(rounds_juntos==2 & sib==0, 0, NA))))%>%
  mutate(round3os= replace(round3os, is.na(round3os), 0)) %>%
  mutate(round4ys= replace(round4ys, is.na(round4ys), 0))%>%
  mutate(round3juntos= round3os * rec_juntos) %>%
  mutate(round4juntos= round4ys * rec_juntos)

                          
new_df_pooled_test<-new_df_pooled%>%
  select(sib, round, rounds_juntos, round3juntos, round4juntos, round3os, round4ys)

reg_estdpool<-plm(estunted~  round3os + round4ys + round3juntos + round4juntos+ rec_juntos +
 age_1 +age_2+age_3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+Iybirth_09+prom_nbi, data= new_df_pooled, index=c("CHILDID"), model= "pooling")

summary(reg_estdpool)
estdpool<- coeftest(reg_estdpool, vcov=vcovHC(reg_estdpool, type="HC0", cluster="group"))
estdpool   
                    
#trying on dataset without na's in outcomes

new_df_sans<- new_df%>%
filter(!is.na(stunted))%>%
  filter(!is.na(estunted))%>%
  filter(!is.na(zhfa))%>%
  filter(!is.na(difstunted))%>%
  filter(!is.na(difestunted))%>%
  filter(!is.na(difzhfa))


new_df_pooled_1<-new_df_sans%>%
  mutate(time_1=1) %>%
  mutate(time_1= ifelse(round==1&sib==0, 2, ifelse(round==0&sib==1, 2, ifelse(round==1&sib==1, 3, NA))))%>%
  mutate(rounds_juntos=replace(time_1, is.na(time_1), 1))


new_df_pooled_1<-new_df_pooled_1%>%
  mutate(round3os= ifelse(rounds_juntos==2 & sib==0, 1, ifelse(rounds_juntos==2 & sib==1, 0, ifelse(rounds_juntos==1 & sib==0, 0, NA)))) %>%
  mutate(round4ys= ifelse(rounds_juntos==3 & sib==1, 1, ifelse(rounds_juntos==2 & sib==1, 0, ifelse(rounds_juntos==2 & sib==0, 0, NA))))%>%
  mutate(round3os= replace(round3os, is.na(round3os), 0)) %>%
  mutate(round4ys= replace(round4ys, is.na(round4ys), 0))%>%
  mutate(round3juntos= round3os * rec_juntos) %>%
  mutate(round4juntos= round4ys * rec_juntos)

                          
new_df_pooled_test_1<-new_df_pooled_1%>%
  select(sib, round, rounds_juntos, round3juntos, round4juntos, round3os, round4ys)

reg_estdpool_1<-plm(estunted~  round3os + round4ys + round3juntos + round4juntos+ rec_juntos +
 age_1 +age_2+age_3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+Iybirth_09+prom_nbi, data= new_df_pooled_1, index=c("CHILDID"), model= "pooling")

summary(reg_estdpool_1)
estdpool<- coeftest(reg_estdpool_1
                    , vcov=vcovHC(reg_estdpool_1
                                  , type="HC0", cluster="group"))
estdpool   
                   

reg_stdpool_1<-plm(stunted~  round3os + round4ys + round3juntos + round4juntos+ rec_juntos +
 age_1 +age_2+age_3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+Iybirth_09+prom_nbi, data= new_df_pooled_1, index=c("CHILDID"), model= "pooling")

summary(reg_stdpool_1)

stdpool<- coeftest(reg_stdpool_1
                    , vcov=vcovHC(reg_stdpool_1
                                  , type="HC0", cluster="group"))
stdpool   

reg_zhfpool_1<-plm(zhfa~  round3os + round4ys + round3juntos + round4juntos+ rec_juntos +
 age_1 +age_2+age_3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+Iybirth_09+prom_nbi, data= new_df_pooled_1, index=c("CHILDID"), model= "pooling")

summary(reg_zhfpool_1)

zhfpool<- coeftest(reg_zhfpool_1
                    , vcov=vcovHC(reg_zhfpool_1
                                  , type="HC0", cluster="group"))
zhfpool 


new_df_ppvt<-new_df_sans%>%
  filter(ppvtlang==4)%>%
  filter(!is.na(ppvtlang))%>%
  filter(!is.na(std_PPVT))%>%
  filter(!is.na(difstd_PPVT))

new_df_pool_ppvt<-new_df_ppvt%>%
  mutate(time_1=1) %>%
  mutate(time_1= ifelse(round==1&sib==0, 2, ifelse(round==0&sib==1, 2, ifelse(round==1&sib==1, 3, NA))))%>%
  mutate(rounds_juntos=replace(time_1, is.na(time_1), 1))


new_df_pool_ppvt<-new_df_pool_ppvt%>%
  mutate(round3os= ifelse(rounds_juntos==2 & sib==0, 1, ifelse(rounds_juntos==2 & sib==1, 0, ifelse(rounds_juntos==1 & sib==0, 0, NA)))) %>%
  mutate(round4ys= ifelse(rounds_juntos==3 & sib==1, 1, ifelse(rounds_juntos==2 & sib==1, 0, ifelse(rounds_juntos==2 & sib==0, 0, NA))))%>%
  mutate(round3os= replace(round3os, is.na(round3os), 0)) %>%
  mutate(round4ys= replace(round4ys, is.na(round4ys), 0))%>%
  mutate(round3juntos= round3os * rec_juntos) %>%
  mutate(round4juntos= round4ys * rec_juntos)

                          
new_df_pool_ppvt_test<-new_df_pool_ppvt%>%
  select(sib, round, rounds_juntos, round3juntos, round4juntos, round3os, round4ys)


reg_ppvt_pool_1<-plm(std_PPVT~ppvt_oth+ round3os + round4ys + round3juntos + round4juntos+ rec_juntos + age_1 +age_2+age_3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+Iybirth_09+prom_nbi, data= new_df_pool_ppvt,index=c("CHILDID"), model= "pooling")
                       
summary(reg_ppvt_pool_1)

ppvtpool<- coeftest(reg_ppvt_pool_1, vcov=vcovHC(reg_ppvt_pool_1
                                  , type="HC0", cluster="group"))
ppvtpool

stargazer( stdpool,estdpool,zhfpool, ppvtpool)
```               

```{r}
#GOAL: trying another technique for number of observations accuracy 

df_obs <- new_df %>% 
  group_by(CHILDID)%>%
  mutate(nb_na = sum(is.na(stunted), is.na(estunted), is.na(zhfa), is.na(difstunted), is.na(difestunted), is.na(difzhfa)))

new_df_obs <- df_obs%>% 
  group_by(CHILDID)%>%
  filter(nb_na==0)%>%
  ungroup()


new_df_obs_pool<-new_df_obs%>%
mutate(round_sib=ifelse(sib==1,round,0))%>% mutate(round_os=ifelse(sib==0,round,0))%>% 
mutate(aftsib=round_sib*rec_juntos)%>% 
mutate(aftos=round_os*rec_juntos)

new_df_pooled_1<-new_df_pooled_1%>%
  mutate(round3os= ifelse(rounds_juntos==2 & sib==0, 1, ifelse(rounds_juntos==2 & sib==1, 0, ifelse(rounds_juntos==1 & sib==0, 0, NA)))) %>%
  mutate(round4ys= ifelse(rounds_juntos==3 & sib==1, 1, ifelse(rounds_juntos==2 & sib==1, 0, ifelse(rounds_juntos==2 & sib==0, 0, NA))))%>%
  mutate(round3os= replace(round3os, is.na(round3os), 0)) %>%
  mutate(round4ys= replace(round4ys, is.na(round4ys), 0))%>%
  mutate(round3juntos= round3os * rec_juntos) %>%
  mutate(round4juntos= round4ys * rec_juntos)

                          
new_df_pooled_test_1<-new_df_pooled_1%>%
  select(sib, round, rounds_juntos, round3juntos, round4juntos, round3os, round4ys)

reg_estdpool_1<-plm(estunted~  round3os + round4ys + round3juntos + round4juntos+ rec_juntos +
 age_1 +age_2+age_3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+Iybirth_09+prom_nbi, data= new_df_pooled_1, index=c("CHILDID"), model= "pooling")

summary(reg_estdpool_1)
estdpool<- coeftest(reg_estdpool_1
                    , vcov=vcovHC(reg_estdpool_1
                                  , type="HC0", cluster="group"))
estdpool   
                   

reg_stdpool_1<-plm(stunted~  round3os + round4ys + round3juntos + round4juntos+ rec_juntos +
 age_1 +age_2+age_3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+Iybirth_09+prom_nbi, data= new_df_pooled_1, index=c("CHILDID"), model= "pooling")

summary(reg_stdpool_1)

stdpool<- coeftest(reg_stdpool_1
                    , vcov=vcovHC(reg_stdpool_1
                                  , type="HC0", cluster="group"))
stdpool   

reg_zhfpool_1<-plm(zhfa~  round3os + round4ys + round3juntos + round4juntos+ rec_juntos +
 age_1 +age_2+age_3+age_4+age_5+age_6+age_7+age_8+age_9+age_10+female+MUMED+CETH+wiR1+Iybirth_01+Iybirth_02+Iybirth_03+Iybirth_04+Iybirth_05+Iybirth_06+Iybirth_07+Iybirth_08+Iybirth_09+prom_nbi, data= new_df_pooled_1, index=c("CHILDID"), model= "pooling")

summary(reg_zhfpool_1)

zhfpool<- coeftest(reg_zhfpool_1
                    , vcov=vcovHC(reg_zhfpool_1
                                  , type="HC0", cluster="group"))
zhfpool 
```


```{r}
magic<- read_dta("index_sibR1R4_B (1).dta")

magic_1<-magic%>%
  mutate(age_4=ifelse(age==4,1,0))%>%
  mutate(age_5=ifelse(age==5,1,0))%>%
  mutate(age_7=ifelse(age==7,1,0))%>%
  mutate(age_6=ifelse(age==6,1,0))%>%
  mutate(age_8=ifelse(age==8,1,0))%>%
  mutate(age_9=ifelse(age==9,1,0))%>%
  mutate(age_10=ifelse(age==10,1,0))%>%
  mutate(age_1= ifelse(age==1, 1,0))%>%
  mutate(age_2= ifelse(age==2,1,0))%>%
  mutate(age_3= ifelse(age==3,1,0))%>%
  mutate(Iybirth_01=ifelse(ybirth==2001,1,0))%>%
  mutate(Iybirth_02=ifelse(ybirth==2002,1,0))%>%
  mutate(Iybirth_03=ifelse(ybirth==2003,1,0))%>%
  mutate(Iybirth_04=ifelse(ybirth==2004,1,0))%>%
  mutate(Iybirth_05=ifelse(ybirth==2005,1,0))%>%
  mutate(Iybirth_06=ifelse(ybirth==2006,1,0))%>%
  mutate(Iybirth_07=ifelse(ybirth==2007,1,0))%>%
  mutate(Iybirth_08=ifelse(ybirth==2008,1,0)) %>%
  mutate(Iybirth_09= ifelse(ybirth==2009,1,0))%>%
  mutate(ppvt_sp = ifelse(ppvtlang== 4, 1, 0))%>%
  mutate(ppvt_spq= ifelse(ppvtlang==3, 1, 0))%>%
  mutate(ppvt_q= ifelse(ppvtlang== 2,1,0))%>%
  mutate(ppvt_oth= ifelse(ppvtlang== 1,1,0))%>%
  filter(!(rec_juntos==2))%>%
  mutate(estunted=as.numeric(estunted))%>%
  mutate(stunted=as.numeric(stunted))%>% 
  filter(juntosgroup!=2)%>%
  filter(baselinejuntos==1)


magic_1<-magic%>%
  filter(sample==1)%>%
  filter(juntosgroup!=2)%>%
  mutate(stunted=as.numeric(stunted))

magic_1<-magic_1%>%
  mutate(stunted= as.numeric(stunted))

pooled_anth<-magic%>%
  filter(sample==1)%>%
  filter(!(rec_juntos==2))%>%
  mutate(estunted=as.numeric(estunted))%>%
  mutate(stunted=as.numeric(stunted))%>% 
  filter(juntosgroup!=2)%>%
  filter(baselinejuntos==1)
  
library(plm)

pooled_stunt<-plm(stunted~round3+round4+round3xjuntos+round4xjuntos+rec_juntos+Iage_1+ Iage_2 + Iage_3 +Iage_4+Iage_5+Iage_6+Iage_7+Iage_8+Iage_9+Iage_10+female+MUMED+CETH+wiR1+Iybirth_2001+Iybirth_2002+Iybirth_2003+Iybirth_2004+Iybirth_2005+Iybirth_2006+Iybirth_2007+Iybirth_2008+Iybirth_2009+prom_nbi,data= magic_1,index=c("CHILDID"),model = "within")#significant, basically what the authors found

pooled_stunt
summary(pooled_stunt)

library(lmtest)
stuntedpool<- coeftest(pooled_stunt
                    , vcov=vcovHC(pooled_stunt,
                                  type="HC0", cluster="group"))
stuntedpool
```
```{r}
hist(magic_1$age_mother)
hist(magic_1$age_caregiver)
hist(magic_1$CAREED)
```
